% 计算功率谱

% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 05-Jul-2022 11:43:32

% 参数
timeLimits = seconds([0 0.9999773]); % 秒
frequencyLimits = [0 22050]; % Hz

%%
% 对感兴趣的信号时间区域进行索引
yt_y_ROI = yt(:,'y');
yt_y_ROI = yt_y_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% 计算频谱估计值
% 不带输出参数运行该函数调用以绘制结果
[Pyt_y_ROI, Fyt_y_ROI] = pspectrum(yt_y_ROI, ...
    'FrequencyLimits',frequencyLimits);

%%
% 对感兴趣的信号时间区域进行索引
y0t_y0_ROI = y0t(:,'y0');
y0t_y0_ROI = y0t_y0_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% 计算频谱估计值
% 不带输出参数运行该函数调用以绘制结果
[Py0t_y0_ROI, Fy0t_y0_ROI] = pspectrum(y0t_y0_ROI, ...
    'FrequencyLimits',frequencyLimits);
